---
apiVersion: v1
kind: Namespace
metadata:
  name: ecopulse

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecopulse
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/ecopulse-mlops-pratham/ecopulse-images/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: REGISTRY_PROJECT
              value: "ecopulse-mlops-pratham"
            - name: MODELS_REPO
              value: "ecopulse-models-generic"
            - name: DATA_BUCKET
              value: "ecopulse-pratham-data"
            - name: DATA_BLOB
              value: "processed/test_split.parquet"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecopulse
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer