electricitymaps:
  base_url: "https://api.electricitymaps.com"
  token: "o3ZjQ0d1U7tC24Ax2E6y"

ingestion:
  signals:
    - carbon-intensity
    - carbon-free-energy
    - price-day-ahead
    - electricity-flows

  endpoint_template: "/v3/{signal}/past-range"

  start: "2024-01-01T00:00:00Z"
  end: "2025-01-01T00:00:00Z"
  chunk_days: 10

  static_params:
    zone: "US-NE-ISNE"
    temporalGranularity: "hourly"

gcs:
  bucket: "ecopulse"
  raw_prefix: "raw"

openmeteo:
  base_url: "https://historical-forecast-api.open-meteo.com/v1/forecast"
  static_params:
    latitude: 39.0465
    longitude: -77.2997
    timezone: "America/New_York"
  
ingestion_weather:
  signals: ["temperature_2m", "relative_humidity_2m", "cloud_cover", "wind_speed_120m", "rain", "snowfall"]
  start: "2024-01-01Z"
  end: "2025-12-31Z"
  chunk_days: 90

# Ensure your existing gcs config is also here
gcs:
  bucket: "ecopulse_bucket"
  raw_prefix: "weather_raw"