# Google Cloud Storage Settings
gcs:
  bucket: "ecopulse_bucket"

# Global Weather API Settings
openmeteo:
  base_url: "https://archive-api.open-meteo.com/v1/archive"
  static_params:
    daily: "weather_code"

# Regional Configurations
locations:
  - name: "northern_virginia"
    latitude: 39.0465
    longitude: -77.2997
    timezone: "America/New_York"
  - name: "portland_oregon"
    latitude: 45.5234
    longitude: -122.6762
    timezone: "America/Los_Angeles"

# Ingestion Logic Settings
ingestion_weather:
  start: "2023-01-01Z"
  end: "2025-12-31Z"
  chunk_days: 30  # Updated to 30 days as requested
  signals:
    - "temperature_2m"
    - "relative_humidity_2m"
    - "rain"
    - "snowfall"
    - "wind_speed_10m"
    - "wind_speed_100m"
    - "cloud_cover"
    - "weather_code"
    - "precipitation"
    - "pressure_msl"
    - "surface_pressure"
    - "shortwave_radiation"
    - "vapour_pressure_deficit"
    - "direct_radiation"